import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const now=()=>new Date().toISOString();
const uid=p=>p+'_'+crypto.randomBytes(8).toString('base64url');
const canon=v=>JSON.stringify(v);
const safe=(a,b)=>{const A=Buffer.from(String(a)),B=Buffer.from(String(b));return A.length===B.length&&crypto.timingSafeEqual(A,B)};
const clean=x=>String(x||'').replace(/[^A-Za-z0-9._:-]/g,'_').slice(0,100);

export function createGameProfile({port,adminToken,serverSecret,dataFile}){
  const secret=crypto.createHmac('sha256',serverSecret).update('JM.GameLiveProfile/0.3').digest();
  const hmac=x=>crypto.createHmac('sha256',secret).update(String(x)).digest('base64url');
  const stateFile=dataFile||path.resolve('./JM_GAME_LIVE_STATE_v0_3.json');
  let state;
  try{state=JSON.parse(fs.readFileSync(stateFile,'utf8'))}catch{state={schema:'JM.GameLiveProfile/0.3',players:{},handles:{},queues:{},matches:{},clans:{},receipts:[],catalog:{supporter:{sku:'supporter',devOnly:true,grants:[{kind:'badge',id:'supporter'}]},founders:{sku:'founders',devOnly:true,grants:[{kind:'cosmetic',id:'founders-mark'}]}}}}
  const save=()=>{fs.mkdirSync(path.dirname(stateFile),{recursive:true});const t=stateFile+'.tmp';fs.writeFileSync(t,JSON.stringify(state,null,2));fs.renameSync(t,stateFile)};
  const receipt=(kind,actor,payload={})=>{const core={schema:'JM.GameReceipt/0.3',receiptId:uid('gr'),at:now(),kind,actor,payload};const receiptHash=crypto.createHash('sha256').update(canon(core)).digest('hex');const r={...core,receiptHash,serverSig:hmac(receiptHash)};state.receipts.push(r);state.receipts=state.receipts.slice(-2000);return r};
  const issue=playerId=>{const p=Buffer.from(JSON.stringify({playerId,at:Date.now(),nonce:uid('n')})).toString('base64url');return p+'.'+hmac(p)};
  const who=req=>{const t=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const i=t.lastIndexOf('.');if(i<1)return null;const p=t.slice(0,i),s=t.slice(i+1);if(!safe(hmac(p),s))return null;try{const j=JSON.parse(Buffer.from(p,'base64url'));return state.players[j.playerId]?j.playerId:null}catch{return null}};
  const body=req=>new Promise((ok,no)=>{let n=0,a=[];req.on('data',c=>{n+=c.length;if(n>131072){no(Error('body too large'));req.destroy()}else a.push(c)});req.on('end',()=>{try{ok(a.length?JSON.parse(Buffer.concat(a)):{} )}catch{no(Error('invalid json'))}});req.on('error',no)});
  const send=(res,status,obj)=>{const raw=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','content-length':Buffer.byteLength(raw)});res.end(raw)};
  const auth=(req,res)=>{const id=who(req);if(!id){send(res,401,{ok:false,error:'player unauthorized'});return null}return id};
  const cloud=async(method,route,token=null,payload=null)=>{const h={'content-type':'application/json'};if(token)h.authorization=(token===adminToken?'Bearer ':'Bearer ')+token;const r=await fetch('http://127.0.0.1:'+port+route,{method,headers:h,body:payload==null?undefined:JSON.stringify(payload)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}};if(!r.ok)throw Error('cloud '+method+' '+route+' -> '+r.status+' '+JSON.stringify(data));return data};
  const viewPlayer=p=>({playerId:p.playerId,handle:p.handle,createdAt:p.createdAt,clanId:p.clanId||null,inventory:p.inventory||[],stats:p.stats||{},activeMatchId:p.activeMatchId||null});
  const role=(m,pid)=>pid===m.hostPlayerId?'host':pid===m.joinPlayerId?'join':null;
  const matchView=(m,pid)=>{const r=role(m,pid);return{matchId:m.matchId,game:m.game,mode:m.mode,state:m.state,createdAt:m.createdAt,updatedAt:m.updatedAt,hostPlayerId:m.hostPlayerId,joinPlayerId:m.joinPlayerId,cloudSpaceId:m.cloudSpaceId,role:r,cloudAccess:r?{base:'/v5/spaces/'+encodeURIComponent(m.cloudSpaceId),memberId:r,credential:m.cloudCredentials[r].credential,rejoinCredential:m.cloudCredentials[r].rejoinCredential,signalEndpoint:'/v5/spaces/'+encodeURIComponent(m.cloudSpaceId)+'/signals',iceEndpoint:'/v5/spaces/'+encodeURIComponent(m.cloudSpaceId)+'/ice'}:null,result:m.result||null,cloudReceipt:m.cloudReceipt||null}};
  const makeMatch=async(a,b,game,mode)=>{const matchId=uid('match'),spaceId=clean('game_'+matchId);const cs=await cloud('POST','/v5/spaces',adminToken,{spaceId,label:'Game match '+matchId,kind:'game-pvp-match',metadata:{profile:'JM.GameLiveProfile/0.3',matchId,game,mode},members:[{id:'host',type:'game-player',label:state.players[a].handle,capabilities:['signal:*','event:write']},{id:'join',type:'game-player',label:state.players[b].handle,capabilities:['signal:*','event:write']} ]});const m={matchId,game,mode,state:'signalling',hostPlayerId:a,joinPlayerId:b,cloudSpaceId:spaceId,cloudCredentials:{host:{credential:cs.credentials.host,rejoinCredential:cs.rejoinCredentials.host},join:{credential:cs.credentials.join,rejoinCredential:cs.rejoinCredentials.join}},createdAt:now(),updatedAt:now()};state.matches[matchId]=m;state.players[a].activeMatchId=matchId;state.players[b].activeMatchId=matchId;receipt('match.created',b,{matchId,spaceId,game,mode});save();return m};
  const completeMatch=async(m,pid,result)=>{const r=role(m,pid);if(r!=='host')throw Error('host authority required');await cloud('POST','/v5/spaces/'+encodeURIComponent(m.cloudSpaceId)+'/events',m.cloudCredentials.host.credential,{event:{type:'game.match.result',payload:result||{}}});await cloud('POST','/v5/spaces/'+encodeURIComponent(m.cloudSpaceId)+'/close',adminToken,{});const cr=await cloud('GET','/v5/spaces/'+encodeURIComponent(m.cloudSpaceId)+'/receipt',adminToken);m.state='complete';m.result=result||{};m.cloudReceipt=cr.receipt;m.updatedAt=now();state.players[m.hostPlayerId].activeMatchId=null;state.players[m.joinPlayerId].activeMatchId=null;receipt('match.complete',pid,{matchId:m.matchId,cloudReceiptHash:cr.receipt?.receiptHash||null});save()};
  async function handle(req,res,u){
    const p=u.pathname;
    if(!p.startsWith('/game/'))return false;
    try{
      if(req.method==='GET'&&p==='/game/v1/meta'){send(res,200,{ok:true,schema:state.schema,root:'JM CLOUD CONTACT SERVER v0.5.1-hosted',route:'PLAYER -> MATCHMAKING -> CLOUD SPACE -> MEMBER -> SIGNAL -> RESULT -> SIGNED RECEIPT',organs:['player_identity','matchmaking','cloud_space_mount','cloud_member_credentials','webrtc_signalling','clans','inventory','dev_entitlements'],boundaries:['TURN relay requires configured cloud TURN secret/URLs','real-money entitlement verification not enabled','public durability remains bounded by Render free carrier persistence']});return true}
      if(req.method==='GET'&&p==='/game/v1/ready'){send(res,200,{ok:true,ready:true,players:Object.keys(state.players).length,matches:Object.keys(state.matches).length,clans:Object.keys(state.clans).length,cloudRoot:'/v5'});return true}
      if(req.method==='POST'&&p==='/game/v1/players/register'){const j=await body(req),handle=String(j.handle||'').trim();if(!/^[A-Za-z0-9_-]{3,20}$/.test(handle)){send(res,400,{ok:false,error:'invalid handle'});return true}const k=handle.toLowerCase();if(state.handles[k]){send(res,409,{ok:false,error:'handle taken'});return true}const playerId=uid('player'),pl={playerId,handle,createdAt:now(),clanId:null,inventory:[],stats:{wins:0,losses:0},activeMatchId:null};state.players[playerId]=pl;state.handles[k]=playerId;const token=issue(playerId),rc=receipt('player.register',playerId,{handle});save();send(res,201,{ok:true,player:viewPlayer(pl),token,receipt:rc});return true}
      if(req.method==='GET'&&p==='/game/v1/me'){const pid=auth(req,res);if(!pid)return true;send(res,200,{ok:true,player:viewPlayer(state.players[pid])});return true}
      if(req.method==='POST'&&p==='/game/v1/matchmaking/join'){const pid=auth(req,res);if(!pid)return true;const j=await body(req),game=clean(j.game||'clashfield'),mode=clean(j.mode||'1v1'),key=game+':'+mode,q=state.queues[key]||[];const peer=q.find(x=>x.playerId!==pid);if(peer){state.queues[key]=q.filter(x=>![peer.playerId,pid].includes(x.playerId));const m=await makeMatch(peer.playerId,pid,game,mode);send(res,200,{ok:true,status:'matched',match:matchView(m,pid)});return true}if(!q.some(x=>x.playerId===pid))q.push({playerId:pid,at:now()});state.queues[key]=q;receipt('queue.join',pid,{game,mode});save();send(res,200,{ok:true,status:'queued',game,mode});return true}
      let mm=p.match(/^\/game\/v1\/matches\/([^/]+)$/);if(req.method==='GET'&&mm){const pid=auth(req,res);if(!pid)return true;const m=state.matches[mm[1]];if(!m||!role(m,pid)){send(res,404,{ok:false,error:'match not found'});return true}send(res,200,{ok:true,match:matchView(m,pid)});return true}
      mm=p.match(/^\/game\/v1\/matches\/([^/]+)\/state$/);if(req.method==='POST'&&mm){const pid=auth(req,res);if(!pid)return true;const m=state.matches[mm[1]];if(!m||!role(m,pid)){send(res,404,{ok:false,error:'match not found'});return true}const j=await body(req);if(j.state==='active'){if(role(m,pid)!=='host'){send(res,403,{ok:false,error:'host authority required'});return true}m.state='active';m.updatedAt=now();receipt('match.active',pid,{matchId:m.matchId});save()}else if(j.state==='complete'){await completeMatch(m,pid,j.result)}else{send(res,400,{ok:false,error:'supported states: active, complete'});return true}send(res,200,{ok:true,match:matchView(m,pid)});return true}
      if(req.method==='POST'&&p==='/game/v1/clans'){const pid=auth(req,res);if(!pid)return true;const j=await body(req),name=String(j.name||'').trim().slice(0,32),tag=String(j.tag||'').trim().toUpperCase().slice(0,6);if(name.length<3||!/^[A-Z0-9]{2,6}$/.test(tag)){send(res,400,{ok:false,error:'invalid clan'});return true}if(state.players[pid].clanId){send(res,409,{ok:false,error:'already in clan'});return true}const clanId=uid('clan'),c={clanId,name,tag,ownerId:pid,createdAt:now(),members:{[pid]:'owner'},invites:{}};state.clans[clanId]=c;state.players[pid].clanId=clanId;receipt('clan.create',pid,{clanId});save();send(res,201,{ok:true,clan:c});return true}
      mm=p.match(/^\/game\/v1\/clans\/([^/]+)\/invite$/);if(req.method==='POST'&&mm){const pid=auth(req,res);if(!pid)return true;const c=state.clans[mm[1]],j=await body(req);if(!c||!['owner','officer'].includes(c.members[pid])){send(res,403,{ok:false,error:'clan permission denied'});return true}const target=state.handles[String(j.handle||'').toLowerCase()];if(!target){send(res,404,{ok:false,error:'player not found'});return true}c.invites[target]={by:pid,at:now()};receipt('clan.invite',pid,{clanId:c.clanId,target});save();send(res,200,{ok:true});return true}
      mm=p.match(/^\/game\/v1\/clans\/([^/]+)\/join$/);if(req.method==='POST'&&mm){const pid=auth(req,res);if(!pid)return true;const c=state.clans[mm[1]];if(!c||!c.invites[pid]){send(res,403,{ok:false,error:'invite required'});return true}if(state.players[pid].clanId){send(res,409,{ok:false,error:'already in clan'});return true}c.members[pid]='member';delete c.invites[pid];state.players[pid].clanId=c.clanId;receipt('clan.join',pid,{clanId:c.clanId});save();send(res,200,{ok:true,clan:c});return true}
      if(req.method==='GET'&&p==='/game/v1/shop/catalog'){send(res,200,{ok:true,catalog:Object.values(state.catalog),realMoney:false});return true}
      if(req.method==='POST'&&p==='/game/v1/shop/dev-grant'){const pid=auth(req,res);if(!pid)return true;const j=await body(req),item=state.catalog[String(j.sku||'')];if(!item||!item.devOnly){send(res,400,{ok:false,error:'DEV_ONLY item required'});return true}for(const g of item.grants)if(!state.players[pid].inventory.some(x=>x.kind===g.kind&&x.id===g.id))state.players[pid].inventory.push({...g,grantedAt:now(),source:'DEV_ONLY'});const rc=receipt('shop.dev-grant',pid,{sku:item.sku});save();send(res,200,{ok:true,inventory:state.players[pid].inventory,receipt:rc,realMoney:false});return true}
      send(res,404,{ok:false,error:'game route not found'});return true
    }catch(e){send(res,400,{ok:false,error:String(e.message||e)});return true}
  }
  return{handle};
}
