import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const now=()=>new Date().toISOString(), uid=p=>p+'_'+crypto.randomBytes(8).toString('base64url'), hash=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const eq=(a,b)=>{const A=Buffer.from(String(a)),B=Buffer.from(String(b));return A.length===B.length&&crypto.timingSafeEqual(A,B)};
export function createServiceMesh({port,adminToken,serverSecret,dataFile}){
 const key=crypto.createHmac('sha256',serverSecret).update('JM.ServiceMesh/0.1').digest(), sig=x=>crypto.createHmac('sha256',key).update(String(x)).digest('base64url');
 const file=dataFile||path.resolve('./JM_SERVICE_MESH_STATE_v0_1.json'); let s;
 try{s=JSON.parse(fs.readFileSync(file,'utf8'))}catch{s={schema:'JM.ServiceMesh/0.1',authusers:{},handles:{},workspaces:{},receipts:[]}}
 const persist=()=>{fs.mkdirSync(path.dirname(file),{recursive:true});const t=file+'.tmp';fs.writeFileSync(t,JSON.stringify(s,null,2));fs.renameSync(t,file)};
 const body=q=>new Promise((ok,no)=>{let n=0,a=[];q.on('data',c=>{n+=c.length;if(n>524288){no(Error('body too large'));q.destroy()}else a.push(c)});q.on('end',()=>{try{ok(a.length?JSON.parse(Buffer.concat(a)):{} )}catch{no(Error('invalid json'))}});q.on('error',no)});
 const send=(r,c,v,t='application/json; charset=utf-8')=>{const raw=t.startsWith('application/json')?JSON.stringify(v):String(v);r.writeHead(c,{'content-type':t,'cache-control':'no-store','content-length':Buffer.byteLength(raw)});r.end(raw)};
 const issue=id=>{const p=Buffer.from(JSON.stringify({id,at:Date.now(),n:uid('n')})).toString('base64url');return p+'.'+sig(p)};
 const who=q=>{const t=String(q.headers.authorization||'').replace(/^Bearer\s+/i,''),i=t.lastIndexOf('.');if(i<1)return null;const p=t.slice(0,i),z=t.slice(i+1);if(!eq(sig(p),z))return null;try{const j=JSON.parse(Buffer.from(p,'base64url'));return s.authusers[j.id]?j.id:null}catch{return null}};
 const auth=(q,r)=>{const id=who(q);if(!id)send(r,401,{ok:false,error:'authuser unauthorized'});return id};
 const cloud=async(method,route,token,payload)=>{const h={'content-type':'application/json'};if(token)h.authorization='Bearer '+token;const rr=await fetch('http://127.0.0.1:'+port+route,{method,headers:h,body:payload==null?undefined:JSON.stringify(payload)});const tx=await rr.text();let j;try{j=JSON.parse(tx)}catch{j={raw:tx}};if(!rr.ok)throw Error('cloud '+method+' '+route+' -> '+rr.status+' '+JSON.stringify(j));return j};
 const rec=(kind,actor,payload)=>{const core={schema:'JM.ServiceMeshReceipt/0.1',receiptId:uid('mr'),at:now(),kind,actor,payload},receiptHash=hash(core),r={...core,receiptHash,meshSig:sig(receiptHash)};s.receipts.push(r);s.receipts=s.receipts.slice(-5000);return r};
 const view=w=>({workspaceId:w.workspaceId,label:w.label,kind:w.kind,ownerId:w.ownerId,createdAt:w.createdAt,updatedAt:w.updatedAt,revision:w.revision,contentHash:w.contentHash||null,cloudSpaceId:w.cloudSpaceId,lastCloudReceiptHash:w.lastCloudReceiptHash||null});
 const page='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>JM Service Mesh v0.1</title><style>body{font-family:system-ui;background:#081018;color:#eef6ff;max-width:850px;margin:auto;padding:24px}.c{border:1px solid #294052;border-radius:18px;padding:18px;margin:14px 0;background:#0d1720}code{background:#152330;padding:2px 6px;border-radius:6px}</style><div class="c"><h1>JM Service Mesh v0.1</h1><b>MESH ≠ MERGE.</b><p>AUTHUSER → WORKSPACE → SAVE → VERIFY → OBSERVE → RECEIPT</p></div><div class="c"><h2>Mounted trio</h2><p>JM RouteVault · JM Receipt Generator · JM Active Keeper Dashboard</p></div><div class="c"><h2>API</h2><code>/mesh/v1/meta</code> · <code>/mesh/v1/workspaces</code> · <code>/mesh/v1/verify</code> · <code>/mesh/v1/dashboard</code></div>';
 async function handle(q,r,u){const p=u.pathname;if(!(p==='/mesh'||p.startsWith('/mesh/')))return false;try{
  if(q.method==='GET'&&p==='/mesh'){send(r,200,page,'text/html; charset=utf-8');return true}
  if(q.method==='GET'&&p==='/mesh/v1/meta'){send(r,200,{ok:true,schema:s.schema,keeper:'MESH ≠ MERGE',route:'AUTHUSER -> WORKSPACE -> SAVE -> VERIFY -> OBSERVE -> RECEIPT',mountedBodies:['JM RouteVault','JM Receipt Generator','JM Active Keeper Dashboard'],cloudRoot:'/v5'});return true}
  if(q.method==='GET'&&p==='/mesh/v1/ready'){send(r,200,{ok:true,ready:true,authusers:Object.keys(s.authusers).length,workspaces:Object.keys(s.workspaces).length,receipts:s.receipts.length});return true}
  if(q.method==='POST'&&p==='/mesh/v1/auth/register'){const j=await body(q),h=String(j.handle||'').trim();if(!/^[A-Za-z0-9_-]{3,24}$/.test(h)){send(r,400,{ok:false,error:'invalid handle'});return true}const k=h.toLowerCase();if(s.handles[k]){send(r,409,{ok:false,error:'handle taken'});return true}const id=uid('auth');s.authusers[id]={authuserId:id,handle:h,createdAt:now()};s.handles[k]=id;const token=issue(id),receipt=rec('authuser.register',id,{handle:h});persist();send(r,201,{ok:true,authuser:s.authusers[id],token,receipt});return true}
  if(q.method==='POST'&&p==='/mesh/v1/workspaces'){const id=auth(q,r);if(!id)return true;const j=await body(q),wid=uid('ws'),sid=('mesh_'+wid).replace(/[^A-Za-z0-9._:-]/g,'_');const cs=await cloud('POST','/v5/spaces',adminToken,{spaceId:sid,label:'Service Mesh '+String(j.label||wid).slice(0,80),kind:'service-mesh-workspace',metadata:{profile:'JM.ServiceMesh/0.1',workspaceId:wid},members:[{id:'authuser',type:'authuser',label:s.authusers[id].handle,capabilities:['event:write','signal:*']}]});const w={workspaceId:wid,label:String(j.label||wid).slice(0,120),kind:String(j.kind||'general').slice(0,64),ownerId:id,createdAt:now(),updatedAt:now(),revision:0,content:null,contentHash:null,cloudSpaceId:sid,cloudCredential:cs.credentials.authuser};s.workspaces[wid]=w;const receipt=rec('workspace.create',id,{workspaceId:wid,cloudSpaceId:sid});persist();send(r,201,{ok:true,workspace:view(w),receipt});return true}
  let m=p.match(/^\/mesh\/v1\/workspaces\/([^/]+)\/save$/);if(q.method==='POST'&&m){const id=auth(q,r);if(!id)return true;const w=s.workspaces[m[1]];if(!w||w.ownerId!==id){send(r,404,{ok:false,error:'workspace not found'});return true}const j=await body(q),rev=w.revision+1,ch=hash(j.content??null);const ev=await cloud('POST','/v5/spaces/'+encodeURIComponent(w.cloudSpaceId)+'/events',w.cloudCredential,{event:{type:'mesh.workspace.saved',payload:{workspaceId:w.workspaceId,revision:rev,contentHash:ch,sourceBody:String(j.sourceBody||'JM RouteVault').slice(0,100)}}});w.content=j.content??null;w.contentHash=ch;w.revision=rev;w.updatedAt=now();const cr=(await cloud('GET','/v5/spaces/'+encodeURIComponent(w.cloudSpaceId)+'/receipt',adminToken)).receipt;w.lastCloudReceiptHash=cr.receiptHash;const receipt=rec('workspace.save',id,{workspaceId:w.workspaceId,revision:rev,contentHash:ch,cloudEventHash:ev.record.hash,cloudReceiptHash:cr.receiptHash});persist();send(r,200,{ok:true,workspace:view(w),receipt,cloudReceipt:cr});return true}
  m=p.match(/^\/mesh\/v1\/workspaces\/([^/]+)$/);if(q.method==='GET'&&m){const id=auth(q,r);if(!id)return true;const w=s.workspaces[m[1]];if(!w||w.ownerId!==id){send(r,404,{ok:false,error:'workspace not found'});return true}send(r,200,{ok:true,workspace:{...view(w),content:w.content}});return true}
  if(q.method==='POST'&&p==='/mesh/v1/verify'){const id=auth(q,r);if(!id)return true;const j=await body(q),h=String(j.receiptHash||''),mr=s.receipts.find(x=>x.receiptHash===h);if(mr){send(r,200,{ok:true,found:'mesh',valid:eq(mr.meshSig,sig(mr.receiptHash)),receipt:mr});return true}const w=Object.values(s.workspaces).find(x=>x.lastCloudReceiptHash===h);if(w&&w.ownerId===id){const cr=(await cloud('GET','/v5/spaces/'+encodeURIComponent(w.cloudSpaceId)+'/receipt',adminToken)).receipt;send(r,200,{ok:true,found:'cloud',valid:cr.receiptHash===h,receipt:cr});return true}send(r,404,{ok:false,error:'receipt not found'});return true}
  if(q.method==='GET'&&p==='/mesh/v1/dashboard'){const id=auth(q,r);if(!id)return true;const ws=Object.values(s.workspaces).filter(w=>w.ownerId===id);send(r,200,{ok:true,dashboard:{authuser:s.authusers[id],workspaceCount:ws.length,workspaces:ws.map(view),latestReceipts:s.receipts.filter(x=>x.actor===id).slice(-20).reverse(),organs:{routeVault:'SAVE/RESTORE',receiptGenerator:'VERIFY',activeKeeperDashboard:'OBSERVE'}}});return true}
  send(r,404,{ok:false,error:'mesh route not found'});return true
 }catch(e){send(r,400,{ok:false,error:String(e.message||e)});return true}}
 return{handle};
}