import {spawn} from 'node:child_process';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const port=18977,base='http://127.0.0.1:'+port,tmp=fs.mkdtempSync(path.join(os.tmpdir(),'jm-market-v02-'));
const env={...process.env,PORT:String(port),HOST:'127.0.0.1',JM_CLOUD_MODE:'development',JM_MARKET_PULSE_ENABLED:'0',JM_CLOUD_ADMIN_TOKEN:'A'.repeat(40),JM_CLOUD_SERVER_SECRET:'S'.repeat(40),JM_CLOUD_DATA:path.join(tmp,'cloud.json'),JM_MARKET_DATA:path.join(tmp,'market.json'),JM_CLOUD_RECEIPT_SIGNING_KEY:path.join(tmp,'key.pem'),JM_GAME_DATA:path.join(tmp,'game.json'),JM_SERVICE_MESH_DATA:path.join(tmp,'mesh.json'),JM_CLOUD_PROFILE_DIR:path.resolve('./profiles'),JM_CLOUD_PROFILE_MANIFEST:path.resolve('./profiles/JM_CLOUD_PROFILE_MANIFEST_HOSTED_v0_5_1.json')};
const child=spawn(process.execPath,['JM_CLOUD_CONTACT_SERVER_v0_5_1_HOSTED_DESCENDANT.mjs'],{env,stdio:['ignore','pipe','pipe']});const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(){for(let i=0;i<80;i++){try{if((await fetch(base+'/ready')).ok)return}catch{}await sleep(100)}throw Error('server did not become ready')}
try{await wait();const page=await fetch(base+'/market'),text=await page.text();if(!page.ok||!text.includes('JM MARKET ECOSYSTEM LAB v1.2')||!text.includes('HOSTED ROUTE')||!text.includes('Load cloud pulse history'))throw Error('v1.2 hosted UI failed');
const meta=await (await fetch(base+'/market/v1/meta')).json();if(meta.schema!=='JM.MarketEcosystemLab.HostedProfile/0.2'||meta.supportedPairs.length!==4)throw Error('market meta failed');
const ready=await (await fetch(base+'/market/v1/ready')).json(),pulse=await (await fetch(base+'/market/v1/pulse')).json(),snaps=await (await fetch(base+'/market/v1/snapshots?limit=10')).json();
if(!ready.ready||pulse.enabled||snaps.count!==0)throw Error('pulse-disabled QA contract failed');
const bad=await fetch(base+'/market/v1/snapshots?symbol=NOPE');if(bad.status!==400)throw Error('snapshot symbol gate failed');
console.log(JSON.stringify({pass:true,tests:['v1.2-hosted-page','dynamic-hosted-route-percentage','session-duration','cloud-pulse-status','bounded-snapshot-route','cloud-history-loader','pulse-disabled-build-isolation','four-pair-contract','unsupported-symbol-gate'],externalQuoteRuntime:'production pulse gate'},null,2));}finally{child.kill('SIGTERM');await sleep(150)}
